//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BizTalk.Adapter.AssemblyExecute.szhjyy.FeiLi.OA.Service {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ECologyServiceSoap", Namespace="http://tempuri.org/")]
    public partial class ECologyService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback QueryBudgetOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateBudgetOperationCompleted;
        
        private System.Threading.SendOrPostCallback Query4SubordinateOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendAlertOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ECologyService(string url) {
            this.Url = url;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event QueryBudgetCompletedEventHandler QueryBudgetCompleted;
        
        /// <remarks/>
        public event UpdateBudgetCompletedEventHandler UpdateBudgetCompleted;
        
        /// <remarks/>
        public event Query4SubordinateCompletedEventHandler Query4SubordinateCompleted;
        
        /// <remarks/>
        public event SendAlertCompletedEventHandler SendAlertCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryBudget", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BudgetVO[] QueryBudget(BudgetVO[] buget) {
            object[] results = this.Invoke("QueryBudget", new object[] {
                        buget});
            return ((BudgetVO[])(results[0]));
        }
        
        /// <remarks/>
        public void QueryBudgetAsync(BudgetVO[] buget) {
            this.QueryBudgetAsync(buget, null);
        }
        
        /// <remarks/>
        public void QueryBudgetAsync(BudgetVO[] buget, object userState) {
            if ((this.QueryBudgetOperationCompleted == null)) {
                this.QueryBudgetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryBudgetOperationCompleted);
            }
            this.InvokeAsync("QueryBudget", new object[] {
                        buget}, this.QueryBudgetOperationCompleted, userState);
        }
        
        private void OnQueryBudgetOperationCompleted(object arg) {
            if ((this.QueryBudgetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryBudgetCompleted(this, new QueryBudgetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateBudget", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BudgetVO[] UpdateBudget(BudgetVO[] buget) {
            object[] results = this.Invoke("UpdateBudget", new object[] {
                        buget});
            return ((BudgetVO[])(results[0]));
        }
        
        /// <remarks/>
        public void UpdateBudgetAsync(BudgetVO[] buget) {
            this.UpdateBudgetAsync(buget, null);
        }
        
        /// <remarks/>
        public void UpdateBudgetAsync(BudgetVO[] buget, object userState) {
            if ((this.UpdateBudgetOperationCompleted == null)) {
                this.UpdateBudgetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateBudgetOperationCompleted);
            }
            this.InvokeAsync("UpdateBudget", new object[] {
                        buget}, this.UpdateBudgetOperationCompleted, userState);
        }
        
        private void OnUpdateBudgetOperationCompleted(object arg) {
            if ((this.UpdateBudgetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateBudgetCompleted(this, new UpdateBudgetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Query4Subordinate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StaffVO[] Query4Subordinate(string StaffKey) {
            object[] results = this.Invoke("Query4Subordinate", new object[] {
                        StaffKey});
            return ((StaffVO[])(results[0]));
        }
        
        /// <remarks/>
        public void Query4SubordinateAsync(string StaffKey) {
            this.Query4SubordinateAsync(StaffKey, null);
        }
        
        /// <remarks/>
        public void Query4SubordinateAsync(string StaffKey, object userState) {
            if ((this.Query4SubordinateOperationCompleted == null)) {
                this.Query4SubordinateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQuery4SubordinateOperationCompleted);
            }
            this.InvokeAsync("Query4Subordinate", new object[] {
                        StaffKey}, this.Query4SubordinateOperationCompleted, userState);
        }
        
        private void OnQuery4SubordinateOperationCompleted(object arg) {
            if ((this.Query4SubordinateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Query4SubordinateCompleted(this, new Query4SubordinateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendAlert", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultVO SendAlert(AlertVO alert) {
            object[] results = this.Invoke("SendAlert", new object[] {
                        alert});
            return ((ResultVO)(results[0]));
        }
        
        /// <remarks/>
        public void SendAlertAsync(AlertVO alert) {
            this.SendAlertAsync(alert, null);
        }
        
        /// <remarks/>
        public void SendAlertAsync(AlertVO alert, object userState) {
            if ((this.SendAlertOperationCompleted == null)) {
                this.SendAlertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendAlertOperationCompleted);
            }
            this.InvokeAsync("SendAlert", new object[] {
                        alert}, this.SendAlertOperationCompleted, userState);
        }
        
        private void OnSendAlertOperationCompleted(object arg) {
            if ((this.SendAlertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendAlertCompleted(this, new SendAlertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BudgetVO {
        
        private System.DateTime oADATEField;
        
        private string kOSTLField;
        
        private string kSTARField;
        
        private string gSBERField;
        
        private string aNLKLField;
        
        private string cURRENCYField;
        
        private decimal aMOUNTField;
        
        private string eXECTYPEField;
        
        private string oPTTYPEField;
        
        private string oAKeyField;
        
        private int sTAFFIDField;
        
        private int cOMPIDField;
        
        private int dEPTIDField;
        
        private string yYYYField;
        
        private string mmField;
        
        private string gPKEYField;
        
        private decimal aMOUNT0Field;
        
        private decimal aMOUNT1Field;
        
        private decimal aMOUNT2Field;
        
        private decimal aMOUNT3Field;
        
        private string mSGTYPField;
        
        private string mSGTXTField;
        
        private string eXTSTRINGField;
        
        /// <remarks/>
        public System.DateTime OADATE {
            get {
                return this.oADATEField;
            }
            set {
                this.oADATEField = value;
            }
        }
        
        /// <remarks/>
        public string KOSTL {
            get {
                return this.kOSTLField;
            }
            set {
                this.kOSTLField = value;
            }
        }
        
        /// <remarks/>
        public string KSTAR {
            get {
                return this.kSTARField;
            }
            set {
                this.kSTARField = value;
            }
        }
        
        /// <remarks/>
        public string GSBER {
            get {
                return this.gSBERField;
            }
            set {
                this.gSBERField = value;
            }
        }
        
        /// <remarks/>
        public string ANLKL {
            get {
                return this.aNLKLField;
            }
            set {
                this.aNLKLField = value;
            }
        }
        
        /// <remarks/>
        public string CURRENCY {
            get {
                return this.cURRENCYField;
            }
            set {
                this.cURRENCYField = value;
            }
        }
        
        /// <remarks/>
        public decimal AMOUNT {
            get {
                return this.aMOUNTField;
            }
            set {
                this.aMOUNTField = value;
            }
        }
        
        /// <remarks/>
        public string EXECTYPE {
            get {
                return this.eXECTYPEField;
            }
            set {
                this.eXECTYPEField = value;
            }
        }
        
        /// <remarks/>
        public string OPTTYPE {
            get {
                return this.oPTTYPEField;
            }
            set {
                this.oPTTYPEField = value;
            }
        }
        
        /// <remarks/>
        public string OAKey {
            get {
                return this.oAKeyField;
            }
            set {
                this.oAKeyField = value;
            }
        }
        
        /// <remarks/>
        public int STAFFID {
            get {
                return this.sTAFFIDField;
            }
            set {
                this.sTAFFIDField = value;
            }
        }
        
        /// <remarks/>
        public int COMPID {
            get {
                return this.cOMPIDField;
            }
            set {
                this.cOMPIDField = value;
            }
        }
        
        /// <remarks/>
        public int DEPTID {
            get {
                return this.dEPTIDField;
            }
            set {
                this.dEPTIDField = value;
            }
        }
        
        /// <remarks/>
        public string YYYY {
            get {
                return this.yYYYField;
            }
            set {
                this.yYYYField = value;
            }
        }
        
        /// <remarks/>
        public string MM {
            get {
                return this.mmField;
            }
            set {
                this.mmField = value;
            }
        }
        
        /// <remarks/>
        public string GPKEY {
            get {
                return this.gPKEYField;
            }
            set {
                this.gPKEYField = value;
            }
        }
        
        /// <remarks/>
        public decimal AMOUNT0 {
            get {
                return this.aMOUNT0Field;
            }
            set {
                this.aMOUNT0Field = value;
            }
        }
        
        /// <remarks/>
        public decimal AMOUNT1 {
            get {
                return this.aMOUNT1Field;
            }
            set {
                this.aMOUNT1Field = value;
            }
        }
        
        /// <remarks/>
        public decimal AMOUNT2 {
            get {
                return this.aMOUNT2Field;
            }
            set {
                this.aMOUNT2Field = value;
            }
        }
        
        /// <remarks/>
        public decimal AMOUNT3 {
            get {
                return this.aMOUNT3Field;
            }
            set {
                this.aMOUNT3Field = value;
            }
        }
        
        /// <remarks/>
        public string MSGTYP {
            get {
                return this.mSGTYPField;
            }
            set {
                this.mSGTYPField = value;
            }
        }
        
        /// <remarks/>
        public string MSGTXT {
            get {
                return this.mSGTXTField;
            }
            set {
                this.mSGTXTField = value;
            }
        }
        
        /// <remarks/>
        public string EXTSTRING {
            get {
                return this.eXTSTRINGField;
            }
            set {
                this.eXTSTRINGField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResultVO {
        
        private bool isSuccessField;
        
        private string messageField;
        
        private string dataField;
        
        /// <remarks/>
        public bool IsSuccess {
            get {
                return this.isSuccessField;
            }
            set {
                this.isSuccessField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AlertVO {
        
        private string jJCDField;
        
        private string dBFLField;
        
        private string dBBTField;
        
        private string dBSXField;
        
        private string jSSJField;
        
        private string cFXTField;
        
        private string jSRField;
        
        /// <remarks/>
        public string JJCD {
            get {
                return this.jJCDField;
            }
            set {
                this.jJCDField = value;
            }
        }
        
        /// <remarks/>
        public string DBFL {
            get {
                return this.dBFLField;
            }
            set {
                this.dBFLField = value;
            }
        }
        
        /// <remarks/>
        public string DBBT {
            get {
                return this.dBBTField;
            }
            set {
                this.dBBTField = value;
            }
        }
        
        /// <remarks/>
        public string DBSX {
            get {
                return this.dBSXField;
            }
            set {
                this.dBSXField = value;
            }
        }
        
        /// <remarks/>
        public string JSSJ {
            get {
                return this.jSSJField;
            }
            set {
                this.jSSJField = value;
            }
        }
        
        /// <remarks/>
        public string CFXT {
            get {
                return this.cFXTField;
            }
            set {
                this.cFXTField = value;
            }
        }
        
        /// <remarks/>
        public string JSR {
            get {
                return this.jSRField;
            }
            set {
                this.jSRField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StaffVO {
        
        private string workCodeField;
        
        private string staffNameField;
        
        /// <remarks/>
        public string WorkCode {
            get {
                return this.workCodeField;
            }
            set {
                this.workCodeField = value;
            }
        }
        
        /// <remarks/>
        public string StaffName {
            get {
                return this.staffNameField;
            }
            set {
                this.staffNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void QueryBudgetCompletedEventHandler(object sender, QueryBudgetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryBudgetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryBudgetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BudgetVO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BudgetVO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void UpdateBudgetCompletedEventHandler(object sender, UpdateBudgetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateBudgetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateBudgetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BudgetVO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BudgetVO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void Query4SubordinateCompletedEventHandler(object sender, Query4SubordinateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Query4SubordinateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Query4SubordinateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StaffVO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StaffVO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void SendAlertCompletedEventHandler(object sender, SendAlertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendAlertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendAlertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultVO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultVO)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591