//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

namespace BizTalk.Adapter.AssemblyExecute.goertek.proxy.inventory
{
    // 
    // This source code was auto-generated by wsdl, Version=4.0.30319.1.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "Gtk_CuVmi_common_ws_provider_inventoryReport_inventoryReportProvider_Binder", Namespace = "http://b2bt.goertek.com:5080/Gtk_CuVmi.common.ws.provider.inventoryReport:invento" +
        "ryReportProvider")]
    public partial class Gtk_CuVmicommonwsproviderinventoryReportinventoryReportProvider : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback inventoryReportOperationCompleted;

        /// <remarks/>
        public Gtk_CuVmicommonwsproviderinventoryReportinventoryReportProvider()
        {
            this.Url = "http://b2bt.goertek.com:5080/ws/Gtk_CuVmi.common.ws.provider.inventoryReport:inve" +
                "ntoryReportProvider/Gtk_CuVmi_common_ws_provider_inventoryReport_inventoryReport" +
                "Provider_Port";
        }
        public Gtk_CuVmicommonwsproviderinventoryReportinventoryReportProvider(string url)
        {
            this.Url = url;
        }

        /// <remarks/>
        public event inventoryReportCompletedEventHandler inventoryReportCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Gtk_CuVmi_common_ws_provider_inventoryReport_inventoryReportProvider_Binder_inven" +
            "toryReport", RequestNamespace = "http://b2bt.goertek.com:5080/Gtk_CuVmi.common.ws.provider.inventoryReport:invento" +
            "ryReportProvider", ResponseNamespace = "http://b2bt.goertek.com:5080/Gtk_CuVmi.common.ws.provider.inventoryReport:invento" +
            "ryReportProvider", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("inventoryReportRes", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public inventoryReportRes inventoryReport([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)] inventoryReportReq inventoryReportReq)
        {
            object[] results = this.Invoke("inventoryReport", new object[] {
                    inventoryReportReq});
            return ((inventoryReportRes)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegininventoryReport(inventoryReportReq inventoryReportReq, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("inventoryReport", new object[] {
                    inventoryReportReq}, callback, asyncState);
        }

        /// <remarks/>
        public inventoryReportRes EndinventoryReport(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((inventoryReportRes)(results[0]));
        }

        /// <remarks/>
        public void inventoryReportAsync(inventoryReportReq inventoryReportReq)
        {
            this.inventoryReportAsync(inventoryReportReq, null);
        }

        /// <remarks/>
        public void inventoryReportAsync(inventoryReportReq inventoryReportReq, object userState)
        {
            if ((this.inventoryReportOperationCompleted == null))
            {
                this.inventoryReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OninventoryReportOperationCompleted);
            }
            this.InvokeAsync("inventoryReport", new object[] {
                    inventoryReportReq}, this.inventoryReportOperationCompleted, userState);
        }

        private void OninventoryReportOperationCompleted(object arg)
        {
            if ((this.inventoryReportCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.inventoryReportCompleted(this, new inventoryReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://b2bt.goertek.com:5080/Gtk_CuVmi.common.ws.provider.inventoryReport:invento" +
        "ryReportProvider")]
    public partial class inventoryReportReq
    {

        private InventoryReport inventoryReportField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InventoryReport InventoryReport
        {
            get
            {
                return this.inventoryReportField;
            }
            set
            {
                this.inventoryReportField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://b2bt.goertek.com:5080/Gtk_CuVmi.common.ws.provider.inventoryReport:invento" +
        "ryReportProvider")]
    public partial class InventoryReport
    {

        private Head headField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Head Head
        {
            get
            {
                return this.headField;
            }
            set
            {
                this.headField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://b2bt.goertek.com:5080/Gtk_CuVmi.common.ws.provider.inventoryReport:invento" +
        "ryReportProvider")]
    public partial class Head
    {

        private string senderQulifierField;

        private string senderIdField;

        private string receiverQualifierField;

        private string receiverIdField;

        private string documentDateField;

        private string documentIdField;

        private string inventoryDateField;

        private string storageCodeField;

        private string storageNameField;

        private string attribute1Field;

        private string attribute2Field;

        private string attribute3Field;

        private Detail[] detailField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SenderQulifier
        {
            get
            {
                return this.senderQulifierField;
            }
            set
            {
                this.senderQulifierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SenderId
        {
            get
            {
                return this.senderIdField;
            }
            set
            {
                this.senderIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReceiverQualifier
        {
            get
            {
                return this.receiverQualifierField;
            }
            set
            {
                this.receiverQualifierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReceiverId
        {
            get
            {
                return this.receiverIdField;
            }
            set
            {
                this.receiverIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DocumentDate
        {
            get
            {
                return this.documentDateField;
            }
            set
            {
                this.documentDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DocumentId
        {
            get
            {
                return this.documentIdField;
            }
            set
            {
                this.documentIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InventoryDate
        {
            get
            {
                return this.inventoryDateField;
            }
            set
            {
                this.inventoryDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StorageCode
        {
            get
            {
                return this.storageCodeField;
            }
            set
            {
                this.storageCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StorageName
        {
            get
            {
                return this.storageNameField;
            }
            set
            {
                this.storageNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Attribute1
        {
            get
            {
                return this.attribute1Field;
            }
            set
            {
                this.attribute1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Attribute2
        {
            get
            {
                return this.attribute2Field;
            }
            set
            {
                this.attribute2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Attribute3
        {
            get
            {
                return this.attribute3Field;
            }
            set
            {
                this.attribute3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Detail", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Detail[] Detail
        {
            get
            {
                return this.detailField;
            }
            set
            {
                this.detailField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://b2bt.goertek.com:5080/Gtk_CuVmi.common.ws.provider.inventoryReport:invento" +
        "ryReportProvider")]
    public partial class Detail
    {

        private string customerPartNumberField;

        private string supplierPartNumberField;

        private string customerCodeField;

        private string customerNameField;

        private string supplierCodeField;

        private string supplierNameField;

        private string defectQtyField;

        private string unknowQtyField;

        private string goodQtyField;

        private string holdQtyField;

        private string unitField;

        private string attribute1Field;

        private string attribute2Field;

        private string attribute3Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerPartNumber
        {
            get
            {
                return this.customerPartNumberField;
            }
            set
            {
                this.customerPartNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SupplierPartNumber
        {
            get
            {
                return this.supplierPartNumberField;
            }
            set
            {
                this.supplierPartNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerCode
        {
            get
            {
                return this.customerCodeField;
            }
            set
            {
                this.customerCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerName
        {
            get
            {
                return this.customerNameField;
            }
            set
            {
                this.customerNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SupplierCode
        {
            get
            {
                return this.supplierCodeField;
            }
            set
            {
                this.supplierCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SupplierName
        {
            get
            {
                return this.supplierNameField;
            }
            set
            {
                this.supplierNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DefectQty
        {
            get
            {
                return this.defectQtyField;
            }
            set
            {
                this.defectQtyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UnknowQty
        {
            get
            {
                return this.unknowQtyField;
            }
            set
            {
                this.unknowQtyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GoodQty
        {
            get
            {
                return this.goodQtyField;
            }
            set
            {
                this.goodQtyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HoldQty
        {
            get
            {
                return this.holdQtyField;
            }
            set
            {
                this.holdQtyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Unit
        {
            get
            {
                return this.unitField;
            }
            set
            {
                this.unitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Attribute1
        {
            get
            {
                return this.attribute1Field;
            }
            set
            {
                this.attribute1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Attribute2
        {
            get
            {
                return this.attribute2Field;
            }
            set
            {
                this.attribute2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Attribute3
        {
            get
            {
                return this.attribute3Field;
            }
            set
            {
                this.attribute3Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://b2bt.goertek.com:5080/Gtk_CuVmi.common.ws.provider.inventoryReport:invento" +
        "ryReportProvider")]
    public partial class Response
    {

        private string documentIdField;

        private string codeField;

        private string messageField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DocumentId
        {
            get
            {
                return this.documentIdField;
            }
            set
            {
                this.documentIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://b2bt.goertek.com:5080/Gtk_CuVmi.common.ws.provider.inventoryReport:invento" +
        "ryReportProvider")]
    public partial class inventoryReportRes
    {

        private Response responseField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Response Response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void inventoryReportCompletedEventHandler(object sender, inventoryReportCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class inventoryReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal inventoryReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public inventoryReportRes Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((inventoryReportRes)(this.results[0]));
            }
        }
    }
}