//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

namespace BizTalk.Adapter.AssemblyExecute.goertek.proxy.receiveAdvice
{
    // 
    // This source code was auto-generated by wsdl, Version=4.0.30319.1.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "Gtk_CuVmi_common_ws_provider_receiveAdvice_receiveAdviceProvider_Binder", Namespace = "http://b2bt.goertek.com:5080/Gtk_CuVmi.common.ws.provider.receiveAdvice:receiveAd" +
        "viceProvider")]
    public partial class Gtk_CuVmicommonwsproviderreceiveAdvicereceiveAdviceProvider : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback receiveAdviceOperationCompleted;

        /// <remarks/>
        public Gtk_CuVmicommonwsproviderreceiveAdvicereceiveAdviceProvider()
        {
            this.Url = "http://b2bt.goertek.com:5080/ws/Gtk_CuVmi.common.ws.provider.receiveAdvice:receiv" +
                "eAdviceProvider/Gtk_CuVmi_common_ws_provider_receiveAdvice_receiveAdviceProvider" +
                "_Port";
        }
        public Gtk_CuVmicommonwsproviderreceiveAdvicereceiveAdviceProvider(string url)
        {
            this.Url = url;
        }

        /// <remarks/>
        public event receiveAdviceCompletedEventHandler receiveAdviceCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Gtk_CuVmi_common_ws_provider_receiveAdvice_receiveAdviceProvider_Binder_receiveAd" +
            "vice", RequestNamespace = "http://b2bt.goertek.com:5080/Gtk_CuVmi.common.ws.provider.receiveAdvice:receiveAd" +
            "viceProvider", ResponseNamespace = "http://b2bt.goertek.com:5080/Gtk_CuVmi.common.ws.provider.receiveAdvice:receiveAd" +
            "viceProvider", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("receiveAdviceRes", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public receiveAdviceRes receiveAdvice([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)] receiveAdviceReq receiveAdviceReq)
        {
            object[] results = this.Invoke("receiveAdvice", new object[] {
                    receiveAdviceReq});
            return ((receiveAdviceRes)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginreceiveAdvice(receiveAdviceReq receiveAdviceReq, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("receiveAdvice", new object[] {
                    receiveAdviceReq}, callback, asyncState);
        }

        /// <remarks/>
        public receiveAdviceRes EndreceiveAdvice(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((receiveAdviceRes)(results[0]));
        }

        /// <remarks/>
        public void receiveAdviceAsync(receiveAdviceReq receiveAdviceReq)
        {
            this.receiveAdviceAsync(receiveAdviceReq, null);
        }

        /// <remarks/>
        public void receiveAdviceAsync(receiveAdviceReq receiveAdviceReq, object userState)
        {
            if ((this.receiveAdviceOperationCompleted == null))
            {
                this.receiveAdviceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreceiveAdviceOperationCompleted);
            }
            this.InvokeAsync("receiveAdvice", new object[] {
                    receiveAdviceReq}, this.receiveAdviceOperationCompleted, userState);
        }

        private void OnreceiveAdviceOperationCompleted(object arg)
        {
            if ((this.receiveAdviceCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.receiveAdviceCompleted(this, new receiveAdviceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://b2bt.goertek.com:5080/Gtk_CuVmi.common.ws.provider.receiveAdvice:receiveAd" +
        "viceProvider")]
    public partial class receiveAdviceReq
    {

        private ReceiveAdvice receiveAdviceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ReceiveAdvice ReceiveAdvice
        {
            get
            {
                return this.receiveAdviceField;
            }
            set
            {
                this.receiveAdviceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://b2bt.goertek.com:5080/Gtk_CuVmi.common.ws.provider.receiveAdvice:receiveAd" +
        "viceProvider")]
    public partial class ReceiveAdvice
    {

        private Head headField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Head Head
        {
            get
            {
                return this.headField;
            }
            set
            {
                this.headField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://b2bt.goertek.com:5080/Gtk_CuVmi.common.ws.provider.receiveAdvice:receiveAd" +
        "viceProvider")]
    public partial class Head
    {

        private string senderQulifierField;

        private string senderIdField;

        private string receiverQualifierField;

        private string receiverIdField;

        private string documentDateField;

        private string documentIdField;

        private string grnNoField;

        private string receiveTypeField;

        private string receiveDateField;

        private string invoiceNoField;

        private string shipToCodeField;

        private string shipToNameField;

        private string customerCodeField;

        private string customerNameField;

        private string supplierCodeField;

        private string supplierNameField;

        private string attribute1Field;

        private string attribute2Field;

        private string attribute3Field;

        private Detail[] detailField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SenderQulifier
        {
            get
            {
                return this.senderQulifierField;
            }
            set
            {
                this.senderQulifierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SenderId
        {
            get
            {
                return this.senderIdField;
            }
            set
            {
                this.senderIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReceiverQualifier
        {
            get
            {
                return this.receiverQualifierField;
            }
            set
            {
                this.receiverQualifierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReceiverId
        {
            get
            {
                return this.receiverIdField;
            }
            set
            {
                this.receiverIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DocumentDate
        {
            get
            {
                return this.documentDateField;
            }
            set
            {
                this.documentDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DocumentId
        {
            get
            {
                return this.documentIdField;
            }
            set
            {
                this.documentIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GrnNo
        {
            get
            {
                return this.grnNoField;
            }
            set
            {
                this.grnNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReceiveType
        {
            get
            {
                return this.receiveTypeField;
            }
            set
            {
                this.receiveTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReceiveDate
        {
            get
            {
                return this.receiveDateField;
            }
            set
            {
                this.receiveDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InvoiceNo
        {
            get
            {
                return this.invoiceNoField;
            }
            set
            {
                this.invoiceNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipToCode
        {
            get
            {
                return this.shipToCodeField;
            }
            set
            {
                this.shipToCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipToName
        {
            get
            {
                return this.shipToNameField;
            }
            set
            {
                this.shipToNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerCode
        {
            get
            {
                return this.customerCodeField;
            }
            set
            {
                this.customerCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerName
        {
            get
            {
                return this.customerNameField;
            }
            set
            {
                this.customerNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SupplierCode
        {
            get
            {
                return this.supplierCodeField;
            }
            set
            {
                this.supplierCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SupplierName
        {
            get
            {
                return this.supplierNameField;
            }
            set
            {
                this.supplierNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Attribute1
        {
            get
            {
                return this.attribute1Field;
            }
            set
            {
                this.attribute1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Attribute2
        {
            get
            {
                return this.attribute2Field;
            }
            set
            {
                this.attribute2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Attribute3
        {
            get
            {
                return this.attribute3Field;
            }
            set
            {
                this.attribute3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Detail", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Detail[] Detail
        {
            get
            {
                return this.detailField;
            }
            set
            {
                this.detailField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://b2bt.goertek.com:5080/Gtk_CuVmi.common.ws.provider.receiveAdvice:receiveAd" +
        "viceProvider")]
    public partial class Detail
    {

        private string customerItemCodeField;

        private string supplierItemCodeField;

        private string receiveQtyField;

        private string attribute1Field;

        private string attribute2Field;

        private string attribute3Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerItemCode
        {
            get
            {
                return this.customerItemCodeField;
            }
            set
            {
                this.customerItemCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SupplierItemCode
        {
            get
            {
                return this.supplierItemCodeField;
            }
            set
            {
                this.supplierItemCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReceiveQty
        {
            get
            {
                return this.receiveQtyField;
            }
            set
            {
                this.receiveQtyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Attribute1
        {
            get
            {
                return this.attribute1Field;
            }
            set
            {
                this.attribute1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Attribute2
        {
            get
            {
                return this.attribute2Field;
            }
            set
            {
                this.attribute2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Attribute3
        {
            get
            {
                return this.attribute3Field;
            }
            set
            {
                this.attribute3Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://b2bt.goertek.com:5080/Gtk_CuVmi.common.ws.provider.receiveAdvice:receiveAd" +
        "viceProvider")]
    public partial class Response
    {

        private string documentIdField;

        private string codeField;

        private string messageField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DocumentId
        {
            get
            {
                return this.documentIdField;
            }
            set
            {
                this.documentIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://b2bt.goertek.com:5080/Gtk_CuVmi.common.ws.provider.receiveAdvice:receiveAd" +
        "viceProvider")]
    public partial class receiveAdviceRes
    {

        private Response responseField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Response Response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void receiveAdviceCompletedEventHandler(object sender, receiveAdviceCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class receiveAdviceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal receiveAdviceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public receiveAdviceRes Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((receiveAdviceRes)(this.results[0]));
            }
        }
    }
}